# Config file for automatic testing at travis-ci.org

language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

matrix:
  fast_finish: true
  exclude:
    # Python/Django combinations that aren't officially supported
    - { python: 3.5, env: DJANGO=2.2 }

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e TOX_ENV
